version: '3.8'
services:
  db:
    image: mysql:8
    container_name: mysqldb_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: book_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      # Wait until MySQL responds "mysqld is alive"
      test: ["CMD", "mysqladmin" ,"ping", "-uroot", "--password=root"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 5s

  app:
    build: .
    container_name: bookdb_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=book_db
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
